DROP DATABASE IF EXISTS yelp;

CREATE DATABASE yelp;

USE yelp;

CREATE TABLE Restaurants (
  resID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  resName VARCHAR(50) NOT NULL,
  overallRating DECIMAL(1, 1) NOT NULL
);

CREATE TABLE Reviews (
  revID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  rating TINYINT NOT NULL,
  reviewText VARCHAR(200) NOT NULL,
  userID INT NOT NULL,
  resID INT NOT NULL REFERENCES Restaurants(resID),
  reviewDate DATE,
  useful INT,
  helpful INT,
  cool INT,
  comment VARCHAR(100),
  commentFrom VARCHAR(50),
  commentCreatedAt DATE
);


CREATE TABLE Photos (
  photoID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  revID INT NOT NULL REFERENCES Reviews(revID),
  imgPath VARCHAR(50) NOT NULL
);




